### ISSUE TITLE
symbol(s) not found for architecture armv7s

### ISSUE THREAD

**Issue by sandeepbol** [realm/realm-cocoa#6320]
## Goals
Compile my app after upgrading from Realm 3.17.3 to 3.20.0

## Expected Results
Successful compilation

## Actual Results

> Showing All Messages
>   "realm::util::InterprocessMutex::s_mutex", referenced from:
> 
>       realm::util::InterprocessMutex::initialize_statics() in shared_realm.o
> 
>       realm::util::InterprocessMutex::free_lock_info() in shared_realm.o
> 
>   "realm::DescriptorOrdering::append_distinct(realm::ColumnsDescriptor)", referenced from:
> 
>       realm::Results::apply_ordering(realm::DescriptorOrdering&&) in results.o
> 
>       realm::Results::distinct(realm::ColumnsDescriptor&&) const in results.o
> 
> ld: symbol(s) not found for architecture armv7s
> 
> /clang:1:1: linker command failed with exit code 1 (use -v to see invocation)
> 

Realm framework version: 3.20.0

Xcode version: Xcode 11.1

iOS/OSX version: 13.1

Dependency manager + version: Cocoapods 1.8.4

**Comment by tgoyne** [comment]
We no longer include the armv7s in the prebuilt binary because Apple no longer recommends using it (it's only relevant for the iPhone 5 and turned out to not be very useful for that). You'll need to also remove armv7s from your app's target architectures if you have an older project. Newly created projects automatically don't target it.
