### ISSUE TITLE
Realm Cocoa 4.1 - Results type is no longer hashable

### ISSUE THREAD

**Issue by ramjyroo** [realm/realm-cocoa#6349]
!!! MANDATORY TO FILL OUT !!!

Create a simple dictionary in swift with the value being any Results<MyRealmObject> - it fails to compile on Xcode 11.2.1 with error 
Showing Recent Errors Only
Type 'Results< MyRealmObject>' does not conform to protocol 'Hashable'

## Expected Results

Till yesterday - this was working as we were using version 3.4.x of realm-cocoa and just upgrading to realm 4.1 where results has become a hashable.

## Actual Results

Compilation failed - Type 'Results< MyRealmObject>' does not conform to protocol 'Hashable'

## Code Sample

`
class MyRealmObject: Object {
   @objc dynamic var id = ""
   @objc dynamic var name = ""
   override static func primaryKey() -> String? {
        return "id"
    }
}
class SomeVc: UIViewController {
   var myLookup: [String: Results<MyRealmObject>]?
}
`

## Version of Realm and Tooling

Realm framework version: 4.1.0

Realm Object Server version: Not applicable

Xcode version: 11.2.1

iOS/OSX version: iOS 13 

Dependency manager + version: Cocoapods 1.8.4

**Comment by tgoyne** [comment]
That code sample works fine. The value type of a dictionary doesn't have to be hashable.

**Comment by ramjyroo** [comment]
Yeah I was also surprised - does not seem to compile. Let me clean build to see if this is a Xcode bug

**Comment by ramjyroo** [comment]
<img width="596" alt="Screen Shot 2019-11-14 at 9 21 12 AM" src="https://user-images.githubusercontent.com/35158533/68825549-75ea5380-06c0-11ea-9d64-36ca437d71e9.png">

**Comment by ramjyroo** [comment]
My Bad - This is NOT failing in the standard dictionary. As a part of dictionary creation - I create a Custom type that required the value to be hashable.

`
extension Results: Hashable {
    public func hash(into hasher: inout Hasher) {
         hasher.combine(self)
    }
}
`

Will something like above be ok to do?

**Comment by tgoyne** [comment]
`hasher.combine(self)` would just be an infinite loop.

There isn't really anything on Results that you could hash that would give a stable useful result. One option could be to wrap it in a class type that hashes its ObjectIdentifier.

**Comment by ericjordanmossman** [comment]
Closing because of tgoyne's input.
