### PR TITLE
Upgrade to core 10.1.1

### LINKED ISSUE #6836: Crashed: Realm notification listener EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
## Goals
Realm shouldn't crash when filtering results

## Expected Results
Realm shouldn't crash when filtering results

## Actual Results
Realm crashes for some users

Crashed: Realm notification listener
0  App                          0x101534478 realm::StringNode<realm::EqualIns>::get_key(unsigned long) + 393368
1  App                          0x10153283c realm::StringNodeEqualBase::find_first_local(unsigned long, unsigned long) + 386140
2  App                          0x101532658 realm::ParentNode::aggregate_local(realm::QueryStateBase*, unsigned long, unsigned long, unsigned long, realm::ArrayPayload*) + 385656
3  App                          0x1014e0470 realm::Query::aggregate_internal(realm::ParentNode*, realm::QueryStateBase*, unsigned long, unsigned long, realm::ArrayPayload*) const + 49296
4  App                          0x1014e4c18 realm::util::FunctionRef<bool (realm::Cluster const*)>::FunctionRef<realm::Query::find_all(realm::ConstTableView&, unsigned long, unsigned long, unsigned long) const::$_4&>(realm::Query::find_all(realm::ConstTableView&, unsigned long, unsigned long, unsigned long) const::$_4&)::'lambda'(void*, realm::Cluster const*)::__invoke(void*, realm::Cluster const*) + 67640
5  App                          0x1014e0c20 realm::Query::find_all(realm::ConstTableView&, unsigned long, unsigned long, unsigned long) const + 51264
6  App                          0x10155e04c realm::ConstTableView::do_sync() + 40800
7  App                          0x1012fd390 realm::_impl::ResultsNotifier::run() + 4313207696
8  App                          0x1012f742c realm::_impl::RealmCoordinator::run_async_notifiers() + 4313183276
9  App                          0x1012f6da8 realm::_impl::RealmCoordinator::on_change() + 4313181608
10 App                          0x1012e4224 realm::_impl::ExternalCommitHelper::listen() + 4313104932
11 App                          0x1012e4d60 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >(void*) + 4313107808
12 libsystem_pthread.dylib        0x1aa8a3914 _pthread_start + 168
13 libsystem_pthread.dylib        0x1aa8ab9d4 thread_start + 8

## Steps for others to Reproduce
An example filtering predicates that caused a crash for a user:
`(type ==[c] "todo" AND meta == "") AND (tags CONTAINS[c] "tag_111_fe0000")`

All the properties involved are indexed properties:
```
  override public class func indexedProperties() -> [String] {
        return ["date", "meta", "type", "tags", "repeatRule"]
  }
```

## Version of Realm and Tooling
Realm framework version: Realm 5.4.7 but using core 6.1.4 because it fixed some issues related to case insensitive search 

Realm Object Server version: NA

Xcode version: 12.0.1

iOS/OSX version: 13.7 & 14.0+

Dependency manager + version: SPM

### LINKED ISSUE #6861: crashes watchOS app after foreground ("terminated due to signal 9")
## Goals
Realm doesn't terminate watchOS app

## Expected Results
above

## Actual Results
v.5.4.7 
- the watchOS's app 1 out of 5 times can terminate when reading\writing in background when active Workout session

v.5.5.0
- the same code as above , crash every time on start of the app

## Steps for others to Reproduce
the watchos app has own database

start the watchOS app -> minimize the application by touching the screen with your palm -> run app (crashes every time for 5.5.0 , not so often for 5.4.7)

## Code Sample

crash logs

**v.5.4.7**

Incident Identifier: C168003D-88A1-4EE7-8847-5E62085BD24B
CrashReporter Key:   1593602e5aa58cf94775ff6286bfdfeb3864687d
Hardware Model:      Watch5,1
Process:             WatchCompanion Extension [423]
Code Type:           ARM (Native)
Role:                unknown
Parent Process:      launchd [1]

OS Version:          Watch OS 7.0 (18R382)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace RUNNINGBOARD, Code 0xdead10cc
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.app.realm.thread.conccurent
Thread 0 Crashed:
0   libsystem_malloc.dylib        	0x1c8a1fbc tiny_size + 396
1   libsystem_malloc.dylib        	0x1c890c2c szone_size + 64
2   libsystem_malloc.dylib        	0x1c890c2c szone_size + 64
3   libsystem_malloc.dylib        	0x1c89b7f8 free + 116
4   Realm                         	0x040e0820 0x3acc000 + 6375456
5   Realm                         	0x040e0814 0x3acc000 + 6375444
6   Realm                         	0x040e0820 0x3acc000 + 6375456
7   Realm                         	0x040e0814 0x3acc000 + 6375444
8   Realm                         	0x040e0820 0x3acc000 + 6375456
9   Realm                         	0x040e0820 0x3acc000 + 6375456
10  Realm                         	0x040e0820 0x3acc000 + 6375456
11  Realm                         	0x040e0820 0x3acc000 + 6375456
12  Realm                         	0x040e0820 0x3acc000 + 6375456
13  Realm                         	0x041198ac 0x3acc000 + 6609068
14  Realm                         	0x04112740 0x3acc000 + 6580032
15  Realm                         	0x041122c4 0x3acc000 + 6578884
16  Realm                         	0x041128e0 0x3acc000 + 6580448
17  Realm                         	0x03c06b68 0x3acc000 + 1289064
18  Realm                         	0x03ede4f0 0x3acc000 + 4269296
19  Realm                         	0x03df9768 0x3acc000 + 3331944
20  RealmSwift                    	0x0519fca8 0x5150000 + 326824
21  RealmSwift                    	0x0519f4a4 0x5150000 + 324772
22  ...ingWatchCompanion Extension	0x02ec58b0 Realm.safeWrite(_:) + 219312 (RealmExtension.swift:18)
23  ...ingWatchCompanion Extension	0x02f1a300 closure #1 in static WorkoutHistoryDataManager.update(_:) + 566016 (WorkoutHistoryDataManager.swift:176)
24  ...ingWatchCompanion Extension	0x02ea6f00 thunk for @callee_guaranteed () -> () + 93952 (<compiler-generated>:0)
25  ...ingWatchCompanion Extension	0x02ea6f6c thunk for @escaping @callee_guaranteed () -> () + 94060 (<compiler-generated>:0)
26  libdispatch.dylib             	0x1c67b240 _dispatch_client_callout + 16
27  libdispatch.dylib             	0x1c689118 _dispatch_sync_invoke_and_complete + 60
28  ...ingWatchCompanion Extension	0x02f16a54 static WorkoutHistoryDataManager.update(_:) + 551508 (WorkoutHistoryDataManager.swift:174)
29  ...ingWatchCompanion Extension	0x02f17520 closure #1 in static WorkoutHistoryDataManager.saveProgramHistory(seconds:avgSpeed:maxSpeed:) + 554272 (WorkoutHistoryDataManager.swift:93)
30  ...ingWatchCompanion Extension	0x02f15de8 thunk for @callee_guaranteed () -> (@owned WorkoutHistory?, @error @owned Error) + 548328 (<compiler-generated>:0)
31  ...ingWatchCompanion Extension	0x02f1a61c thunk for @callee_guaranteed () -> (@owned WorkoutHistory?, @error @owned Error)partial apply + 566812 (<compiler-generated>:0)
32  libswiftDispatch.dylib        	0x4611455c partial apply for thunk for @callee_guaranteed () -> + 42332 (@out A, @error @owned Error) + 20
33  libswiftDispatch.dylib        	0x46112f0c closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>+ 36620 (fn:execute:rescue:) + 108
34  libswiftDispatch.dylib        	0x4611457c partial apply for closure #1 in closure #1 in OS_dispatch_queue._syncHelper<A>+ 42364 (fn:execute:rescue:) + 20
35  libswiftDispatch.dylib        	0x461144cc partial apply for thunk for @callee_guaranteed () -> + 42188 () + 20
36  libswiftDispatch.dylib        	0x46114784 thunk for @callee_guaranteed () -> + 42884 ()partial apply + 12
37  libswiftDispatch.dylib        	0x46112cbc thunk for @escaping @callee_guaranteed () -> + 36028 () + 20
38  libdispatch.dylib             	0x1c67b240 _dispatch_client_callout + 16
39  libdispatch.dylib             	0x1c689118 _dispatch_sync_invoke_and_complete + 60
40  libswiftDispatch.dylib        	0x46113750 implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>+ 38736 (execute:) + 152
41  libswiftDispatch.dylib        	0x46113d0c partial apply for implicit closure #2 in implicit closure #1 in OS_dispatch_queue.sync<A>+ 40204 (execute:) + 40
42  libswiftDispatch.dylib        	0x46112dac OS_dispatch_queue._syncHelper<A>+ 36268 (fn:execute:rescue:) + 228
43  libswiftDispatch.dylib        	0x461133a4 OS_dispatch_queue.sync<A>+ 37796 (execute:) + 140
44  ...ingWatchCompanion Extension	0x02f170e0 static WorkoutHistoryDataManager.saveProgramHistory(seconds:avgSpeed:maxSpeed:) + 553184 (WorkoutHistoryDataManager.swift:77)
45  ...ingWatchCompanion Extension	0x030aa3d4 UIProgramWalkController.finishedTrainigDay() + 2204628 (UIProgramWalkController.swift:263)
46  ...ingWatchCompanion Extension	0x030a9b2c UIProgramWalkController.sessionWasFinished() + 2202412 (UIProgramWalkController.swift:252)
47  ...ingWatchCompanion Extension	0x030a85f8 closure #1 in UIProgramWalkController.startSessionTimerWith(seconds:) + 2196984 (UIProgramWalkController.swift:199)
48  ...ingWatchCompanion Extension	0x02f2c884 thunk for @escaping @callee_guaranteed (@guaranteed NSTimer) -> () + 641156 (<compiler-generated>:0)
49  Foundation                    	0x1d92395c __NSFireTimer + 64
50  CoreFoundation                	0x1cc49378 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 28
51  CoreFoundation                	0x1cc48f7c __CFRunLoopDoTimer + 992
52  CoreFoundation                	0x1cc48478 __CFRunLoopDoTimers + 324
53  CoreFoundation                	0x1cc428b0 __CFRunLoopRun + 1896
54  CoreFoundation                	0x1cc41c28 CFRunLoopRunSpecific + 572
55  GraphicsServices              	0x20dce4c0 GSEventRunModal + 160
56  UIKitCore                     	0x3df631fc -[UIApplication _run] + 1104
57  UIKitCore                     	0x3df68750 UIApplicationMain + 140
58  WatchKit                      	0x3272cbfc WKExtensionMain + 760
59  libdyld.dylib                 	0x1c6bc94c start + 4

Thread 1 name:  com.apple.uikit.eventfetch-thread
Thread 1:
0   libsystem_kernel.dylib        	0x1c82e824 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x1c82dc80 mach_msg + 72
2   CoreFoundation                	0x1cc480b4 __CFRunLoopServiceMachPort + 376
3   CoreFoundation                	0x1cc425e8 __CFRunLoopRun + 1184
4   CoreFoundation                	0x1cc41c28 CFRunLoopRunSpecific + 572
5   Foundation                    	0x1d7c2680 -[NSRunLoop+ 30336 (NSRunLoop) runMode:beforeDate:] + 228
6   Foundation                    	0x1d7c2560 -[NSRunLoop+ 30048 (NSRunLoop) runUntilDate:] + 88
7   UIKitCore                     	0x3dffd2e0 -[UIEventFetcher threadMain] + 152
8   Foundation                    	0x1d92293c __NSThread__start__ + 844
9   libsystem_pthread.dylib       	0x1c8cdf04 _pthread_start + 288
10  libsystem_pthread.dylib       	0x1c8d65c8 thread_start + 8

Thread 2 name:  Realm notification listener
Thread 2:
0   libsystem_kernel.dylib        	0x1c854304 kevent + 8
1   Realm                         	0x03b367ac 0x3acc000 + 436140
2   Realm                         	0x03b3b8c0 0x3acc000 + 456896
3   Realm                         	0x03b3b834 0x3acc000 + 456756
4   Realm                         	0x03b3b74c 0x3acc000 + 456524
5   Realm                         	0x03b3aaa8 0x3acc000 + 453288
6   libsystem_pthread.dylib       	0x1c8cdf04 _pthread_start + 288
7   libsystem_pthread.dylib       	0x1c8d65c8 thread_start + 8

Thread 3:
0   libsystem_pthread.dylib       	0x1c8d65b4 start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	0x1c8d65b4 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000003680040   x1: 0x0000000014b94e80   x2: 0x0000000014b00000   x3: 0x0000000014b91400
    x4: 0x0000000000000020   x5: 0x0000000014b911c0   x6: 0x0000000000000030   x7: 0x000000001cdadca8
    x8: 0x0000000000000002   x9: 0x0000000014b93dc0  x10: 0x0000000003688500  x11: 0x0000000000000500
   x12: 0x0000000010100001  x13: 0x000000000000090f  x14: 0x0000000000000001  x15: 0x00000000d500dd15
   x16: 0x000000001c89b784  x17: 0x0000000000028480  x18: 0x0000000000000000  x19: 0x0000000014b94e80
   x20: 0x000000000367c000  x21: 0x0000000014bed2f0  x22: 0x0000000014bed2f0  x23: 0x000000004c997000
   x24: 0x000000004c997000  x25: 0x0000000014050c48  x26: 0x0000000000a00000  x27: 0x0000000014050a48
   x28: 0x0000000014050a18   fp: 0x000000000363ffa0   lr: 0x000000001c890c2c
    sp: 0x000000000363ff90   pc: 0x000000001c8a1fbc cpsr: 0x80000000
   esr: 0x56000080  Address size fault

------

**v.5.5.0**

Incident Identifier: 448ADEAE-1544-4F60-9F88-C34906D5D999
CrashReporter Key:   1593602e5aa58cf94775ff6286bfdfeb3864687d
Hardware Model:      Watch5,1
Process:             WatchCompanion Extension [501]
Code Type:           ARM (Native)
Role:                unknown
Parent Process:      launchd [1]

OS Version:          Watch OS 7.0 (18R382)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace RUNNINGBOARD, Code 0xdead10cc
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x1c82e824 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x1c82dc80 mach_msg + 72
2   CoreFoundation                	0x1cc480b4 __CFRunLoopServiceMachPort + 376
3   CoreFoundation                	0x1cc425e8 __CFRunLoopRun + 1184
4   CoreFoundation                	0x1cc41c28 CFRunLoopRunSpecific + 572
5   GraphicsServices              	0x20dce4c0 GSEventRunModal + 160
6   UIKitCore                     	0x3df631fc -[UIApplication _run] + 1104
7   UIKitCore                     	0x3df68750 UIApplicationMain + 140
8   WatchKit                      	0x3272cbfc WKExtensionMain + 760
9   libdyld.dylib                 	0x1c6bc94c start + 4

Thread 1:
0   libsystem_pthread.dylib       	0x1c8d65b4 start_wqthread + 0

Thread 2 name:  com.apple.uikit.eventfetch-thread
Thread 2:
0   libsystem_kernel.dylib        	0x1c82e824 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x1c82dc80 mach_msg + 72
2   CoreFoundation                	0x1cc480b4 __CFRunLoopServiceMachPort + 376
3   CoreFoundation                	0x1cc425e8 __CFRunLoopRun + 1184
4   CoreFoundation                	0x1cc41c28 CFRunLoopRunSpecific + 572
5   Foundation                    	0x1d7c2680 -[NSRunLoop+ 30336 (NSRunLoop) runMode:beforeDate:] + 228
6   Foundation                    	0x1d7c2560 -[NSRunLoop+ 30048 (NSRunLoop) runUntilDate:] + 88
7   UIKitCore                     	0x3dffd2e0 -[UIEventFetcher threadMain] + 152
8   Foundation                    	0x1d92293c __NSThread__start__ + 844
9   libsystem_pthread.dylib       	0x1c8cdf04 _pthread_start + 288
10  libsystem_pthread.dylib       	0x1c8d65c8 thread_start + 8

Thread 3 name:  Realm notification listener
Thread 3:
0   libsystem_kernel.dylib        	0x1c854304 kevent + 8
1   Realm                         	0x031e5b98 0x317c000 + 433048
2   Realm                         	0x031eacac 0x317c000 + 453804
3   Realm                         	0x031eac20 0x317c000 + 453664
4   Realm                         	0x031eab38 0x317c000 + 453432
5   Realm                         	0x031e9e94 0x317c000 + 450196
6   libsystem_pthread.dylib       	0x1c8cdf04 _pthread_start + 288
7   libsystem_pthread.dylib       	0x1c8d65c8 thread_start + 8

Thread 4:
0   libsystem_pthread.dylib       	0x1c8d65b4 start_wqthread + 0

Thread 5:
0   libsystem_pthread.dylib       	0x1c8d65b4 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000010004005   x1: 0x0000000007000806   x2: 0x0000000000000000   x3: 0x0000000000000c00
    x4: 0x0000000000001603   x5: 0x00000000ffffffff   x6: 0x0000000000000000   x7: 0x00000000130800d0
    x8: 0x00000000fffffbbf   x9: 0x0000000007000906  x10: 0x000000007a2c0002  x11: 0x000000007a2c0002
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x1c45e24d49d44f9a
   x16: 0xffffffffffffffe1  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x00000000ffffffff  x21: 0x0000000000001603  x22: 0x0000000000000c00  x23: 0x0000000002f82be4
   x24: 0x0000000007000806  x25: 0x0000000000000000  x26: 0x0000000007000806  x27: 0x0000000000001603
   x28: 0x0000000002f82b9c   fp: 0x0000000002f82aa0   lr: 0x000000001c82dc80
    sp: 0x0000000002f82a50   pc: 0x000000001c82e824 cpsr: 0x60000000
   esr: 0x56000080  Address size fault

Realm framework version: 5.4.7 and 5.5.0 

Xcode version: 12.0.1

iOS/OSX version: iOS 14 , watchOS 7.0

### LINKED ISSUE #6874: Semantic Issue
!!! MANDATORY TO FILL OUT !!!

## Goals

Compile Realm version 10.0.0 in Xcode version 12.0.1

## Expected Results

Realm library threw a compile error, a semantic issue. I am using Xcode's Swift Package Manager.
`Aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer`

## Actual Results

Following are some of the logs reported by Xcode.

`SourcePackages/checkouts/realm-core/src/realm/alloc.hpp:546:19: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer
inline Allocator::~Allocator() noexcept
`
`SourcePackages/checkouts/realm-core/src/realm/alloc.hpp:328:5: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer
    ~WrappedAllocator()
`

## Steps for others to Reproduce

Compile using Xcode 12.0.1 and integrating Realm library through Xcode's Swift Package Manager.

## Version of Realm and Tooling

ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2

/Applications/Xcode.app/Contents/Developer
Xcode 12.0.1
Build version 12A7300

/usr/local/bin/pod
1.9.3
(not in use here)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

carthage not found
(not in use here)

/usr/local/bin/git
git version 2.28.0

### LINKED ISSUE #6914: Release compilation issue using Swift PM
## Goals

Build project with Realm via Swift Package Manager

## Expected Results

The project to build successfully, but it doesn't (However it works ok with same version on Cocoapods)

## Actual Results

Showing All Messages
/Users/dave/Library/Developer/Xcode/DerivedData/TestRealm-cexqmmixscidkqairqvranppknzi/SourcePackages/checkouts/realm-core/src/realm/alloc.hpp:328:5: Aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on iOS 11 or newer

## Steps for others to Reproduce

1. Create a new Xcode project - i'm using 12.1. I don't change any of the defaults. 
2. iOS deployment target is 14.1
3. I add swift package dependency at repo: https://github.com/realm/realm-cocoa
4. I do an archive/release build
5. It doesn't build

(note that if I use Cocoapods, then it works ok)

## Version of Realm and Tooling

Realm framework version: ?

Realm Object Server version: ?

Xcode version: 12.1

iOS/OSX version: 14.1 / Mac 10.13.6

Dependency manager + version: Swift PM

### PR DESCRIPTION
**Pull request by tgoyne**
Fixes #6861. Fixes #6836. Fixes #6914. Fixes #6874.

### CODE REVIEW

**Comment by tgoyne** [comment]
retest this please
