### ISSUE TITLE
@State macro expansion fails on backtick-escaped where property in SwiftUI.swift (Xcode 27 Beta)

### ISSUE THREAD

**Issue by karlingen** [realm/realm-cocoa#8828]
## Summary

Building realm-swift with Xcode 27 Beta fails due to the `@State` property declarations using backtick-escaped keyword names in RealmSwift/SwiftUI.swift. The Swift compiler's `@State` macro expansion does not correctly handle backtick-escaped keyword identifiers, producing multiple compilation errors.

This is separate from the realm-core C++ build failure tracked in #8827.

## Environment

- Xcode 27 Beta 1
- realm-swift 20.0.4
- Swift 6 compiler

## Errors

The macro expansion of:

```swift
@State public var `where`: ((Query<ResultType>) -> Query<Bool>)?
```

generates invalid code, producing errors like:

- `consecutive declarations on a line must be separated by ';'`
- `'$' is not an identifier`

This occurs in two locations in RealmSwift/SwiftUI.swift:
- `ObservedResults` struct
- `ObservedSectionedResults` struct

## Minimal Reproducer

This is a Swift compiler bug with `@State` and backtick-escaped keywords. It can be reproduced independently of realm-swift:

```swift
import SwiftUI

struct Example: View {
    @State var `where`: String? = nil
    var body: some View { Text("test") }
}
```

## Suggested Fix

Rename the `@State` stored property from ``  `where`  `` to a non-keyword name (e.g. `whereFilter`), while keeping the `where:` parameter label on the public init signatures unchanged. This preserves source compatibility at the call site.

This has also been reported to Apple as a Swift compiler bug: **FB23015259**.

## Related

- #8827 — Xcode 27 build failure (realm-core C++ issue)
- https://github.com/realm/realm-core/pull/8096 — realm-core fix for the separate C++ issue

**Comment by Huaian666** [comment]
can reproduce this consistently. happens when the input is empty for me. took me way too long to narrow down

**Comment by hiSandog** [comment]
This is a useful Xcode beta compatibility report. A minimal model that uses only the backtick-escaped `where` property and `@State` would make it much easier to see whether the macro expansion fails before Realm code is involved. It would also help to mention whether renaming the property is a viable workaround or whether persisted schema compatibility prevents that.

**Comment by karlingen** [comment]
This specific issue should be fixed in Xcode 27 Beta 5 and macOS 27 Beta 5
