### ISSUE TITLE
RealmSwift 5.5.1 Xcode 12.5 binaries please

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-cocoa#7228]
## Goals
Build existing app with RealmSwift v5.5.1 with Xcode 12.5

Current latest v5.5.1 is not supported with Xcode 12.5

EDIT:  Sorry I mean a version with Realm Cloud Sync since just a the local version can be used with Package Manager.

Can be just Intel binary as per current release since I don't believe there is any plan to produce a universal version for Intel/M1

**Comment by ericjordanmossman** [comment]
@tgoyne @jsflax 
Do we just need to make a v5 release that includes [this](https://github.com/realm/realm-cocoa/pull/7227)?
Or is there anything additional needed?

**Comment by cliftonlabrum** [comment]
Installing Realm works with Swift Package Manager in Xcode 12.5.

**Comment by huawt** [comment]
combine.swift  line:38
'Identifiable' is only available in application extensions for iOS 13 or newer

**Comment by diegomontoya** [comment]
Our MacOS catalyst is breaking under xcode 12.5. iOS build is fine for some reason. 

```module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler: CIBuild/build/Debug-maccatalyst/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64-apple-ios-macabi.swiftmodule```

**Comment by ChuanqingYang** [comment]
> combine.swift line:38
> 'Identifiable' is only available in application extensions for iOS 13 or newer

same issue

**Comment by farruhnet** [comment]
> combine.swift line:38
> 'Identifiable' is only available in application extensions for iOS 13 or newer

Same, please fix

**Comment by MarkoFirst** [comment]
+, I have same problem

**Comment by KonstantinMiha** [comment]
+, same problem

**Comment by genpictures** [comment]
Same problem. Please fix

**Comment by farruhnet** [comment]
After updating to 10.7.4 the problem was solved

**Comment by MarkoFirst** [comment]
> После обновления до 10.7.4 проблема решилась

How did U do that? U are from the future?)))

![image](https://user-images.githubusercontent.com/25689913/116393640-95c8f500-a82a-11eb-8b39-2a503ba460a9.png)

**Comment by farruhnet** [comment]
> > После обновления до 10.7.4 проблема решилась
> 
> How did U do that? U are from the future?)))
> 
> ![image](https://user-images.githubusercontent.com/25689913/116393640-95c8f500-a82a-11eb-8b39-2a503ba460a9.png)
> ![image](https://user-images.githubusercontent.com/25689913/116393844-d163bf00-a82a-11eb-9c92-74d74bd806d5.png)

![изображение](https://user-images.githubusercontent.com/9885079/116393900-a9308c00-a83b-11eb-86cc-bb4b589a9d4b.png)

it was released yesterday =)
In my podfile.lock
<img width="221" alt="изображение" src="https://user-images.githubusercontent.com/9885079/116393969-c2393d00-a83b-11eb-88b0-b37f3c050495.png">

**Comment by MarkoFirst** [comment]
> 
> ![изображение](https://user-images.githubusercontent.com/9885079/116393900-a9308c00-a83b-11eb-86cc-bb4b589a9d4b.png)
> 
> it was released yesterday =)
> 
> Pardon in my podfile.lock, is 10.7.2
> <img alt="изображение" width="221" src="https://user-images.githubusercontent.com/9885079/116393969-c2393d00-a83b-11eb-88b0-b37f3c050495.png">

Thank you so much!

**Comment by duncangroenewald** [comment]
> Installing Realm works with Swift Package Manager in Xcode 12.5.

With Realm Sync ??  I don't think so.

**Comment by duncangroenewald** [comment]
> @tgoyne @jsflax
> Do we just need to make a v5 release that includes [this](https://github.com/realm/realm-cocoa/pull/7227)?
> Or is there anything additional needed?

No don't add anything - just an intel binary version that can be used with Xcode 12.5.  Not the end of the world if that can't be done easily since we can just keep using Xcode 12.4 but there are some XCode bug fixes in 12.5 that we want :-)

**Comment by kingnight** [comment]
Same problem. Please release  RealmSwift 5.5.1 build with Xcode 12.5

**Comment by JonyFang** [comment]
Xcode 12.5 binaries has been added to the [release-v10.7.4](https://github.com/realm/realm-cocoa/releases/tag/v10.7.4)  package. `pod update Realm RealmSwift` will work.

**Comment by duncangroenewald** [comment]
@JonyFang - if that was meant for me we can't upgrade from 5.5.1 to 10.7.4 yet since we are using Realm Cloud sync.

**Comment by mungbeans2** [comment]
Realm/RealmSwift 10.7.4 does NOT work with Xcode 12.5 (12E262):

Undefined symbols for architecture arm64:
  "protocol descriptor for Swift.Identifiable", referenced from:
      l_got.$ss12IdentifiableMp in libRealmSwift.a(Combine.o)
  "Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer<A>) -> (Swift.IndexingIterator<Swift._ArrayBuffer<A>>, Swift.Int)", referenced from:
      generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray<A where A: Swift.Collection>(A) -> Swift.ContiguousArray<A.Element> in libRealmSwift.a(Object.o)
ld: symbol(s) not found for architecture arm64

**Comment by duncangroenewald** [comment]
Thanks guys, will test it
