### ISSUE TITLE
Unable to use prebuilt dynamic framework with Xcode 10.2.1

### ISSUE THREAD

**Issue by cb-swissprime** [realm/realm-cocoa#6196]
!!! MANDATORY TO FILL OUT !!!

## Goals
Update my project so that I can use it in Xcode 10.2.1 and so that I can migrate it to Swift 5

## Expected Results
The project compiles

## Actual Results
I get the following error message: `Module compiled with Swift 4.2 cannot be imported by the Swift 5.0.1 compiler`

## Steps to Reproduce

1. Download the realm dynamic framework binaries from [here](https://static.realm.io/downloads/swift/realm-swift-3.17.0.zip)
2. Add them to the project as described [here](https://realm.io/docs/swift/latest#installation). Follow instructions under the tab "Dynamic Framework"
3. Build project

## Version of Realm and Tooling

I downloaded version 3.17.0 of realm and used Xcode 10.2.1

Realm framework version: 3.17.0

Realm Object Server version: ?

Xcode version: 10.2.1

iOS/OSX version: ?

Dependency manager + version: ?

Any help is appreciated, thanks!

**Comment by cb-swissprime** [comment]
Ok I figured it out. My app consists of an app and a framework project. The compilation error occurred in my framework project and I forgot to update the Realm and RealmSwift frameworks in my framework project :(. Once I updated them there, it worked.
