### ISSUE TITLE
Pod failed to build Realm

### ISSUE THREAD

**Issue by liuxuan30** [realm/realm-cocoa#5600]
## Goals
Trying to release a new version of ChartsRealm framework with Realm 3.1.1 for pod today.

However when trying to do pod trunk push:
pod reports below errors:
```
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  Realm/Realm/ObjectStore/src/binding_callback_thread_observer.cpp:19:10: fatal error: 'binding_callback_thread_observer.hpp' file not found
    - NOTE  | xcodebuild:  Realm/Realm/ObjectStore/src/impl/collection_change_builder.cpp:19:10: fatal error: 'impl/collection_change_builder.hpp' file not found
    - NOTE  | [tvOS] xcodebuild:  Realm/Realm/ObjectStore/src/collection_notifications.cpp:19:10: fatal error: 'collection_notifications.hpp' file not found
    - NOTE  | [tvOS] xcodebuild:  Realm/Realm/ObjectStore/src/impl/collection_notifier.cpp:19:10: fatal error: 'impl/collection_notifier.hpp' file not found
```
pod spec is [here](https://github.com/danielgindi/ChartsRealm/blob/master/ChartsRealm.podspec) 
Project page: https://github.com/danielgindi/ChartsRealm/

carthage seems fine though, with prebuilt framework.

## Expected Results
pod could compile Realm 3.1.1 and push succeed

## Actual Results
failed.

## Steps to Reproduce
I just update podspec and run pod trunk push

## Version of Realm and Tooling
Realm framework version: 3.1.1
Xcode version: Latest GM
Dependency manager + version: ? pod 1.4.0

**Comment by bdash** [comment]
Please follow the [steps for troubleshooting problems with CocoaPods](https://realm.io/docs/swift/latest/#cocoapods) listed in our documentation, and report back.

There were [effectively no changes between v3.1.1 and the prior release](https://github.com/realm/realm-cocoa/compare/v3.1.0...v3.1.1), so this seems likely to be a problem on your end.

**Comment by liuxuan30** [comment]
seems cleaning the cache solved the issues. Thanks!

**Comment by liuxuan30** [comment]
@bdash hi sorry to bother again. I am facing new issues, as after clean up the cache and rebuild,
pod starts to complain
```
   Testing with xcodebuild. 
 -> ChartsRealm (3.0.5)
    - ERROR | xcodebuild: Returned an unsuccessful exit code.
    - ERROR | xcodebuild:  ChartsRealm/ChartsRealm/Classes/Data/RealmBarDataSet.swift:208:24: error: type 'RLMArray<RLMObject>' does not conform to protocol 'Sequence'
reported here https://github.com/CocoaPods/CocoaPods/issues/7410

**Comment by bdash** [comment]
RLMArray only conforms to Swift's `Sequence` if you include RLMSupport.swift in your target.

**Comment by liuxuan30** [comment]
That's seems not true, as the ChartsRealm is written in Swift, so it's using RealmSwift in the first place? The weird thing is, using Xcode to build directly is totally fine. I don't find the project include `RLMSupport.swift` at all

**Comment by bdash** [comment]
`RLMArray` isn't a RealmSwift type, it's a Realm type. RealmSwift doesn't do anything to try and make Realm's Objective-C types more ergonomic. Instead it provides its own types that are naturally ergonomic in Swift. `RLMSupport.swift` is what improves the ergonomics of the Objective-C types. It needs to be explicitly included in a project to be used.

**Comment by liuxuan30** [comment]
yes I understood. But since Xcode build just fine, I'm thinking it's not related to RLMSupport.swift. As the project produced a demo app and it works fine.

**Comment by liuxuan30** [comment]
Oh sorry, I find RLMSupport.swift in the folder, but not added into Xcode. I think that's the reason why it builds then.
