### PR TITLE
Add support for building Realm & RealmSwift for tvOS

### PR DESCRIPTION
**Pull request by kishikawakatsumi**
- [x] [Notifier] Watch changes for tvOS without pipes

### CODE REVIEW

**Comment by jpsim** [comment]
Thanks for your work on this, @kishikawakatsumi! Once you've added back in the RLMNotifier approach, you can close #2506 and we can use this PR as the defacto standard branch for tvOS.

**Comment by kishikawakatsumi** [comment]
I've just updated https://github.com/realm/realm-cocoa/pull/2721 to use GM build of core/framework, change default directory to Library/Caches, encryption disabled, and inter-process notification is disabled.

You can use pre-release version of Realm & RealmSwift for tvOS, like following:

```
pod 'Realm', git: 'https://github.com/realm/realm-cocoa', branch: 'kk-tvos'
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa', branch: 'kk-tvos'
```

**Comment by jpsim** [comment]
@kishikawakatsumi now that #2756 has been merged, could you please re-apply these changes? It should be simpler now that we're sharing build settings among schemes.

**Comment by kishikawakatsumi** [comment]
@jpsim Rebased #2756 other than unit tests on tvOS simulators. I'm working on re-enable unit tests.

**Comment by jpsim** [comment]
Thanks for the hard work on this, @kishikawakatsumi, keep it up!

**Comment by kishikawakatsumi** [comment]
Unit tests on simulator now works again.

**Comment by jpsim** [comment]
CI is failing due to hitting assertion failures: https://ci.realm.io/job/objc_pr/2271/configuration=Debug,swift_version=1.2,target=osx-swift/console and https://ci.realm.io/job/objc_pr/2271/configuration=Release,swift_version=2.1,target=ios-device-objc/console

```
Test Suite 'KVOTests' started at 2015-11-05 17:08:38 +0000
Test Case '-[RealmSwift_Tests.KVOTests testAllPropertyTypesMultipleAccessors]' started.
Assertion failed: (ret >= 0), function listen, file /Users/realm/workspace/objc_pr/configuration/Debug/swift_version/1.2/target/osx-swift/tightdb_objc/Realm/ObjectStore/impl/apple/external_commit_helper.cpp, line 222.

Testing failed:
	testAllPropertyTypesMultipleAccessors() encountered an error (Test session exited(-1) without completing. If you believe this error represents a bug, please attach the log file at /var/folders/bj/n03qf0s968d07kcp9bc4v_vw0000gl/T/com.apple.dt.XCTest-status/Session-2015-11-05_09:07:14-bUfEnr.log)
** TEST FAILED **
```

and 

```
Test Suite 'iOS static tests.xctest' started at 2015-11-05 09:13:07.029
Test Suite 'ArrayPropertyTests' started at 2015-11-05 09:13:07.029
Test Case '-[ArrayPropertyTests testAddInvalidated]' started.
2015-11-05 09:13:07.460 TestHost[9068:60b] WARNING: An RLMRealm instance was deallocated during a write transaction and all pending changes have been rolled back. Make sure to retain a reference to the RLMRealm for the duration of the write transaction.
Assertion failed: (ret >= 0), function listen, file /Users/realm/workspace/objc_pr/configuration/Release/swift_version/2.1/target/ios-device-objc/tightdb_objc/Realm/ObjectStore/impl/apple/external_commit_helper.cpp, line 222.
** TEST FAILED **
```

**Comment by kishikawakatsumi** [comment]
@jpsim Thanks! I didn't notice those assertion failures. I've confirmed fixing locally and rebased it.

**Comment by kishikawakatsumi** [comment]
I've still not seen running tests on AppleTV devices from a command line. But they are succeeded running from Xcode (⌘ + U). So now @jp could you try to execute on CI machine?

**Comment by jpsim** [comment]
I'll look into testing on device, sure. Yesterday you said that there were still a few failures when running from Xcode, do those now pass?

**Comment by kishikawakatsumi** [comment]
> Yesterday you said that there were still a few failures when running from Xcode, do those now pass?

@jpsim Yes, the failures are due to invoke abstract class as tests from Xcode when I execute tests from "Test Navigator" pane. It won't occur when executing tests from "⌘ + U".

```
class RealmCollectionTypeTests: TestCase {
    var str1: SwiftStringObject!
    var str2: SwiftStringObject!
    var collection: AnyRealmCollection<SwiftStringObject>!

    func getCollection() -> AnyRealmCollection<SwiftStringObject> {
        fatalError("abstract")
    }

    func getAggregateableCollection() -> AnyRealmCollection<SwiftAggregateObject> {
        fatalError("abstract")
    }
```

**Comment by jpsim** [comment]
ok great

**Comment by kishikawakatsumi** [comment]
@jpsim 

Device tests on tvOS from command line freezes in `replacing existing signature`. It cannot launch TestHost.app. :cry: 

Log:
```
Probing signature of /Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Products/Release-appletvos/Tests.xctest/Frameworks/libswiftXCTest.dylib
  /usr/bin/xcrun '--toolchain' '/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain' 'codesign' '-r-' '--display' '/Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Products/Release-appletvos/Tests.xctest/Frameworks/libswiftXCTest.dylib'

Touch build/DerivedData/Realm/Build/Products/Release-appletvos/Tests.xctest
    cd /Users/katsumi/Desktop/Realm/realm-cocoa
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/libexec:/usr/local/bin:/usr/bin:/bin:/usr/libexec:/Users/katsumi/.nodebrew/current/bin:/usr/local/heroku/bin:/Users/katsumi/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/katsumi/Desktop/infer/infer/bin"
    /usr/bin/touch -c /Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Products/Release-appletvos/Tests.xctest

CodeSign build/DerivedData/Realm/Build/Products/Release-appletvos/Tests.xctest
    cd /Users/katsumi/Desktop/Realm/realm-cocoa
    export CODESIGN_ALLOCATE=/Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/libexec:/usr/local/bin:/usr/bin:/bin:/usr/libexec:/Users/katsumi/.nodebrew/current/bin:/usr/local/heroku/bin:/Users/katsumi/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/katsumi/Desktop/infer/infer/bin"
    
Signing Identity:     "iPhone Developer: Katsumi Kishikawa (9NXEJ2L8Q6)"

    /usr/bin/codesign --force --sign 26C896B60A13E38F0F5C81E60B2A786234BE5F9F --timestamp=none /Users/katsumi/Desktop/Realm/realm-cocoa/build/DerivedData/Realm/Build/Products/Release-appletvos/Tests.xctest

writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/wr/f0q3fd5976nd8fwpwk717btr0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/3d7cf2c566bf62d201eb7903faa4db87/dfc1205d89010714a4c87e1c710b0e651568377a/ManifestCache.plist
/var/folders/wr/f0q3fd5976nd8fwpwk717btr0000gn/T/A18A38CB-22F9-4B0F-B683-2F5712748D0B-49424-00005C6608C9D5D0/tmp/XCTest.framework: replacing existing signature
/var/folders/wr/f0q3fd5976nd8fwpwk717btr0000gn/T/A18A38CB-22F9-4B0F-B683-2F5712748D0B-49424-00005C6608C9D5D0/tmp/IDEBundleInjection.framework: replacing existing signature
```

**Comment by bdash** [comment]
I saw an issue like that when working on refactoring the Xcode projects. IIRC I resolved it by rebooting the device and / or my computer.

**Comment by jpsim** [comment]
My solution to running tvOS tests on device is somewhat inelegant, but fairly trivial.

`xcodebuild` fails to run tvOS framework unit tests on physical devices, but has no issues whatsoever running unit tests for an application.

So I've shared the `TestHost` scheme and added both test suites as its "testables".

To run Objective-C and Swift tests independently would require sharing two test host schemes, but because both these test suites only take a few seconds to run I opted to combine both sets of tests.

I should be able to set this up in the office on CI early next week (the TV is no longer attached to CI at the moment because I was testing it directly).

**Comment by jpsim** [comment]
One major limitation about the current device tests is that test output isn't logged other than `*** Tests Succeeded ***` or `*** Tests Failed ****`. We could set up some remote logging if we find that it's necessary, but I'm not inclined to do that immediately.

**Comment by kishikawakatsumi** [comment]
@jpsim Thank you very much to be able to run tests on devices! I've pushed tvOS examples (response cache sample and pre-loaded readonly data sample). Please review thouse if you get a chance.

**Comment by jpsim** [comment]
simulator & device tests now run (and pass! :tada:) on CI.

https://ci.realm.io/job/objc_pr/2408/configuration=Release,swift_version=2.1,target=tvos/console
https://ci.realm.io/job/objc_pr/2408/configuration=Release,swift_version=2.1,target=tvos-device/console

**Comment by azoff** [comment]
@kishikawakatsumi can't seem to get Realm (core) to build in xcode 7.1 using a4e49b7. Is there a relatively stable commit in this branch you recommend using? I'm getting errors specifically in the recently added code. Here's the I'm seeing in case you're interested:

```
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:47:52: No member named 'listen' in 'realm::_impl::ExternalCommitHelper'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:50:31: Use of undeclared identifier 'm_thread'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:60:18: Use of undeclared identifier 'm_thread'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:65:38: Unknown type name 'm_realms_mutex'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:79:5: Use of undeclared identifier 'm_realms'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:84:38: Unknown type name 'm_realms_mutex'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:85:44: Use of undeclared identifier 'm_realms'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:90:13: Use of undeclared identifier 'm_realms'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:97:28: Out-of-line definition of 'listen' does not match any declaration in 'realm::_impl::ExternalCommitHelper'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:104:38: Unknown type name 'm_realms_mutex'
Pods/Realm/Realm/ObjectStore/impl/apple/external_commit_helper.cpp:105:30: Use of undeclared identifier 'm_realms'
```

In case it's not obvious, I've tried installing the branch using CocoaPods using [the suggested dependency targets](https://github.com/realm/realm-cocoa/pull/2721#issuecomment-150617652).

**Comment by kishikawakatsumi** [comment]
@azoff Thank you for pointing out! I forgot to push a commit. It's my bad. 
I've fixed and rebased to master, then pushed. Can you try again?

**Comment by azoff** [comment]
@kishikawakatsumi yes that worked!

**Comment by jpsim** [comment]
I've updated this PR to use core's 0.95.1 release, which contains tvOS slices. We should then be able to merge this pending #2914.

File: examples/tvos/objc/DownloadCache/AppDelegate.h [hunk 1]
```diff
@@ -0,0 +1,15 @@
+//
```
Comment (tgoyne) [inline examples/tvos/objc/DownloadCache/AppDelegate.h]: These files need the correct license header.

File: examples/tvos/objc/DownloadCache/RepositoriesViewController.m [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+                    for (NSDictionary *item in items) {
+                        Repository *repository = [Repository new];
+                        repository.identifier = [NSString stringWithFormat:@"%@", item[@"id"]];
+                        repository.name = item[@"name"];
+                        repository.avatarURL = item[@"owner"][@"avatar_url"];
+
+                        [realm addOrUpdateObject:repository];
+                    }
+                }];
+                dispatch_async(dispatch_get_main_queue(), ^{
```
Comment (tgoyne) [inline examples/tvos/objc/DownloadCache/RepositoriesViewController.m]: This hits the race condition where the async dispatch arrives before the refresh. Reloading in a realm notification block instead would fix that and would also reduce nesting.

**Comment by kishikawakatsumi** [comment]
Addressed feedback.

**Comment by tgoyne** [comment]
Remaining CI failure is a missing provisioning profile for the tv device. Code changes look good to me.

**Comment by jpsim** [comment]
The tvOS machine should have the appropriate provisioning profile. I re-bootstrapped all the CI machines yesterday (after this job was last run), so I'm now rerunning the job for the last commit to see if that helps at all.

**Comment by jpsim** [comment]
@kishikawakatsumi @bdash @tgoyne I think this is ready to go.

**Comment by jpsim** [comment]
@kishikawakatsumi if you have time, it'd be nice to update the examples to use Realm notifications.

**Comment by kishikawakatsumi** [comment]
:+1:

File: Configuration/Realm/Tests.xcconfig [hunk 3]
```diff
@@ -1,10 +1,11 @@
-SUPPORTED_PLATFORMS = macosx iphonesimulator iphoneos;
+SUPPORTED_PLATFORMS = macosx iphonesimulator iphoneos appletvos appletvsimulator;
 SKIP_INSTALL = YES;
 
 INFOPLIST_FILE = Realm/Tests/RealmTests-Info.plist;
 PRODUCT_BUNDLE_IDENTIFIER = io.Realm.${PRODUCT_NAME:rfc1034identifier};
 
 LD_RUNPATH_SEARCH_PATHS[sdk=iphone*] = $(inherited) @executable_path/Frameworks @loader_path/Frameworks;
+LD_RUNPATH_SEARCH_PATHS[sdk=appletv*] = $(inherited) @executable_path/Frameworks @loader_path/Frameworks;
 LD_RUNPATH_SEARCH_PATHS[sdk=macosx*] = $(inherited) @executable_path/../Frameworks @loader_path/../Frameworks;
```
Comment (bdash) [inline Configuration/Realm/Tests.xcconfig]: Should this also be set for the watch?

Comment (bdash) [inline Configuration/Realm/Tests.xcconfig]: On that note: Is this setting necessary for tvOS? Presumably we're running the tests successfully for watchOS without it set, so is it necessary for tvOS?

Comment (jpsim) [inline Configuration/Realm/Tests.xcconfig]: Probably.

File: Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme [hunk 4]
```diff
@@ -0,0 +1,111 @@
+<?xml version="1.0" encoding="UTF-8"?>
```
Comment (bdash) [inline Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme]: I don't think a TestHost scheme on its own is useful. Is this intentional?

File: Configuration/Realm/Tests.xcconfig (hunk 3 above)
Comment (jpsim) [inline Configuration/Realm/Tests.xcconfig]: We're not running watchOS tests. When we last looked into it, it wasn't possible to do so, but I don't think we've confirmed that in a while.

File: Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme (hunk 4 above)
Comment (jpsim) [inline Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme]: Yes, this is intentional. See the commit message for 600b29f2b1cda45f25dccad5f39432b0d7882636.

File: Realm/ObjectStore/impl/apple/external_commit_helper.cpp [hunk 5]
```diff
@@ -32,6 +32,87 @@
 using namespace realm;
 using namespace realm::_impl;
 
+#if TARGET_OS_TV
```
Comment (bdash) [inline Realm/ObjectStore/impl/apple/external_commit_helper.cpp]: In the future we should look to split the tvOS version of this into a separate file from the iOS + Mac implementation.

File: build.sh [hunk 6]
```diff
@@ -216,18 +203,19 @@ test_ios_devices() {
...
-    scheme="$1"
-    configuration="$2"
-    failed=0
+    local sdk="$1"
+    local scheme="$2"
+    local configuration="$3"
+    local failed=0
     for device in "${serial_numbers[@]}"; do
-        xc "-scheme '$scheme' -configuration $configuration -destination 'id=$device' test" || failed=1
+        xc "-scheme '$scheme' -configuration $configuration -destination 'id=$device' -sdk $sdk test" || failed=1
```
Comment (bdash) [inline build.sh]: Why is it necessary to pass `-sdk …` here?

Comment (jpsim) [inline build.sh]: Because `xcodebuild` can't distinguish between an iOS or tvOS based on the `id` alone.

File: Configuration/Realm/Tests.xcconfig (hunk 3 above)
Comment (bdash) [inline Configuration/Realm/Tests.xcconfig]: Part of the reason I ask is that the same setting was also absent from Realm.xcconfig. Perhaps we've just not had reports of it causing an issue yet since I'm guessing it may be a regression on master from my Xcode project refactoring.

Comment (jpsim) [inline Configuration/Realm/Tests.xcconfig]: That's possible. One way to figure this out would be to either write tests for watchOS if it's now possible, or manually try it.

File: build.sh (hunk 6 above)
Comment (bdash) [inline build.sh]: I guess that's why the destination specifier has a `platform` component. We could specify it instead, but it may be less convenient to conjure it up than the SDK name.

**Comment by kishikawakatsumi** [comment]
@jpsim I've updated to use notification block.

File: Realm/ObjectStore/impl/apple/external_commit_helper.cpp (hunk 5 above)
Comment (tgoyne) [inline Realm/ObjectStore/impl/apple/external_commit_helper.cpp]: On the async queries branch I've mostly unified the two versions so that nearly all of the code is shared, but that depends on the earlier restructuring.

Comment (bdash) [inline Realm/ObjectStore/impl/apple/external_commit_helper.cpp]: Nice!

File: Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme (hunk 4 above)
Comment (bdash) [inline Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme]: Is there a radar about this issue?

**Comment by bdash** [comment]
:+1:

File: Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme (hunk 4 above)
Comment (jpsim) [inline Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme]: No, but there's a long twitter thread where others confirm this as an issue here: https://twitter.com/simjp/status/665250128656142337

File: build.sh [hunk 7]
```diff
@@ -949,6 +996,22 @@ case "$COMMAND" in
         zip --symlinks -r realm-swift-framework-watchos.zip RealmSwift.framework Realm.framework
         ;;
 
+    "package-tvos")
+        cd tightdb_objc
+        REALM_SWIFT_VERSION=2.0 sh build.sh tvos
```
Comment (tgoyne) [inline build.sh]: Needs to be updated to 2.1.1

**Comment by tgoyne** [comment]
A 2.5MB binary blob for test data is sorta excessive. The repo is already bloated enough that it won't add all that much to the clone time, but it triples the size of the zip downloaded for CI jobs.

File: Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme (hunk 4 above)
Comment (bdash) [inline Realm.xcodeproj/xcshareddata/xcschemes/TestHost.xcscheme]: That Twitter thread implies the issue is fixed in Xcode 7.1.1+. Is it? If not, filing a Radar would be a good idea.

File: build.sh (hunk 7 above)
Comment (jpsim) [inline build.sh]: Nice catch! Updated.

**Comment by jpsim** [comment]
> A 2.5MB binary blob for test data is sorta excessive.

Ouch, I hadn't noticed it was that large. I've culled the data down to just places in California and then compacted the file, so now it's about ~200KB.
