### ISSUE TITLE
include of non-modular header inside framework module 'Realm' with Xcode8.3 and Carthage

### ISSUE THREAD

**Issue by pocket7878** [realm/realm-cocoa#4792]
**Bugs**: 

Can't build with Xcode8.3 with Carthage.

## Steps to Reproduce

1. Update Xcode to 8.3(8E162)
2. Setup Cartfile
```
github "realm/realm-cocoa"
```
3. remove old `Carthage` folder
```
rm -rf Carthage`
```

3. Run `carthage update realm-cocoa --platform ios`

### Terminal Output
```
*** Downloading realm-cocoa.framework binary at "v2.4.4"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.0.2 and the local version is 3.1."
*** Checking out realm-cocoa at "v2.4.4"
*** xcodebuild output can be found in /var/folders/mf/pn032fpj4dqbfky075_45z180000gn/T/carthage-xcodebuild.7qXaHP.log
*** Building scheme "Realm" in Realm.xcworkspace
*** Building scheme "RealmSwift" in Realm.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/masato/Documents/azit-projects/crew-ios/Carthage/Checkouts/realm-cocoa/Carthage/Realm.xcworkspace -scheme RealmSwift -configuration Release -derivedDataPath /Users/masato/Library/Caches/org.carthage.CarthageKit/DerivedData/realm-cocoa/v2.4.4 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/mf/pn032fpj4dqbfky075_45z180000gn/T/carthage-xcodebuild.7qXaHP.log
```

### Log
 
```
....
Carthage/Checkouts/realm-cocoa/Realm/Realm.h:21:9: error: include of non-modular header inside framework module 'Realm'
....
````

## Version of Realm and Tooling
```
ProductName:	Mac OS X
ProductVersion:	10.12.4
BuildVersion:	16E195

/Applications/Xcode.app/Contents/Developer
Xcode 8.3
Build version 8E162

/Users/masato/.rbenv/shims/pod
1.2.0


/usr/local/bin/bash
GNU bash, バージョン 4.4.12(1)-release (x86_64-apple-darwin16.3.0)

/usr/local/bin/carthage
0.20.1
github "realm/realm-cocoa" "v2.4.4"

/usr/local/bin/git
git version 2.12.0
hub version 2.3.0-pre9
```

```
carthage version
0.20.1
```

https://github.com/realm/realm-cocoa/issues/4783

**Comment by luckytianyiyan** [comment]
try this way:
```shell
$ carthage bootstrap --no-use-binaries
```

```shell
$ carthage help bootstrap

...
[--no-use-binaries]
	check out dependency repositories even when prebuilt frameworks exist, disabled if --use-submodules option is present
	(ignored if --no-build option is present)
...
```

**Comment by pocket7878** [comment]
@luckytianyiyan Thank you for your comment!!
May be this issue was solved by newly released `v2.5.0` thanks!

**Comment by effzehn** [comment]
Interestingly, I have the same issue with 2.5 with `--no-use-binaries`.
Using the standard option to built binaries actually works, since 2.5 seems to use a binary built with Swift 3.1.

**Comment by jpsim** [comment]
@effzehn Please file a new bug report and provide all of the information listed in the new issue template.
