### ISSUE TITLE
Swift-1.2 fails to build

### ISSUE THREAD

**Issue by ReDetection** [realm/realm-cocoa#2941]
Hello. I'm getting a lot of duplications. Can anyone confirm this? realm from commit `d856361b56b06f1a7bc975eeb8cb37fd15103a74` fails. Build settings seems to be right, no duplicates there.
```
duplicate symbol _llvm.cmdline in:
    /Users/me/project/Pods/Realm/core/librealm-ios.a(bptree-iPhoneSimulator-bitcode.o)
    /Users/me/project/Pods/Realm/core/librealm-ios.a(disable_sync_to_disk-iPhoneSimulator-bitcode.o)
duplicate symbol _llvm.embedded.module in:
    /Users/me/project/Pods/Realm/core/librealm-ios.a(bptree-iPhoneSimulator-bitcode.o)
    /Users/me/project/Pods/Realm/core/librealm-ios.a(disable_sync_to_disk-iPhoneSimulator-bitcode.o)
ld: 96 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1504

/Applications/Xcode7.app/Contents/Developer
Xcode 7.1
Build version 7B91b

/usr/bin/pod
0.39.0
Realm (0.96.2)
RealmSwift (0.96.2)
Realm (from `https//github.com/realm/realm-cocoa.git`, branch `swift-1.2`)
RealmSwift (from `https//github.com/realm/realm-cocoa.git`, branch `swift-1.2`)

/bin/bash
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)

/usr/local/bin/carthage
0.9.2
(not in use here)

/usr/bin/git
git version 2.4.9 (Apple Git-60)
```

**Comment by bdash** [comment]
Realm includes two prebuilt versions of its core library: with bitcode support for Xcode 7, and without bitcode support for Xcode 6.4. Your error message shows that the version with bitcode support is being used. Realm determines which version of the core library to use based on the version of Xcode that `xcode-select` says is active at the time `pod install` was run. In your case, Xcode 7 was active, but you intend to build using Xcode 6.4.

To address this you can do the following:
1. `rm -rf Pods`
2. `sudo xcode-select -s /Applications/Xcode-6.4.app`
3. `pod install`
4. `sudo xcode-select -r`

This will temporarily select Xcode 6.4 as the active command-line tools, reinstall your pods from CocoaPods, then reset the active command-line tools to the current version of Xcode.

**Comment by ReDetection** [comment]
So realm pod depends on system state during `pod install`. 
Ah, and [I see it in build.sh](https://github.com/realm/realm-cocoa/blob/master/build.sh#L768-L773). 
Unfortunately, output of `prepare_command` is [suppressed by `set -e`](https://github.com/CocoaPods/CocoaPods/blob/691e3de4405a0b7174ccd9ca85912a045d286aa2/lib/cocoapods/installer/pod_source_preparer.rb#L63). Maybe reopen https://github.com/CocoaPods/CocoaPods/pull/1850, how do you think?

**Comment by ReDetection** [comment]
Or make support for bitcode explicit, e.g. with pod subspecs? they will differ only in that `prepare_command` field, one will pass option for bitcode into `build.sh`, another will not.

**Comment by ReDetection** [comment]
Another question: how do you know you should build without bitcode? I can't find the condition, can you please point it out?  
I'm asking because I was on d856361b56b06f1a7bc975eeb8cb37fd15103a74 commit and wasn't able to build until changed to the latest 900733e1141ac2eda675c03fefc8d4574c41d391.

**Comment by bdash** [comment]
I personally don't know enough about CocoaPods subspecs to know whether they're appropriate to use for this purpose. Perhaps @jpsim or @mrackwitz have thoughts on that side of things.

Whether or not to build with bitcode depends on the version of Xcode you're using. Bitcode support is new in Xcode 7. Older versions don't support it, and attempting to use it will result in link errors. That's the only relevant factor. I'm not sure why you'd have had issues with d856361 but not 900733e. I don't see any changes in that range that I would expect to cause build failures.

I think it would be reasonable to say that the swift-1.2 branch should always builds with bitcode disabled, since Swift 1.2 support inherently means that Xcode 6.x is being used.

**Comment by ReDetection** [comment]
> swift-1.2 branch should always builds with bitcode disabled

very reasonable :+1:

**Comment by mrackwitz** [comment]
That should work from now on automatically with the right Xcode version.
